version: "3.9"

services:

  backend:
    container_name: backend_doctor_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: doctor-appointment-backend
    ports:
      - "5000:4000"
    env_file:
      - ./backend/.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend_doctor_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: doctor-appointment-frontend
    ports:
      - "3000:80"
    restart: always

  admin:
    container_name: admin_doctor_app
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: doctor-appointment-admin
    ports:
      - "3001:80"
    restart: always
