services:
  backend:
    build: ./backend
    container_name: backend_${COMPOSE_PROJECT_NAME}
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: npm start

  frontend:
    build: ./frontend
    container_name: frontend_${COMPOSE_PROJECT_NAME}
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
    command: npm run dev

  admin:
    build: ./admin
    container_name: admin_${COMPOSE_PROJECT_NAME}
    ports:
      - "3001:3001"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    volumes:
      - ./admin:/app
    command: npm run dev
