services:

  backend:
    build: ./backend
    container_name: backend_doctor-appointment
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend_doctor-appointment
    ports:
      - "3000:80"

  admin:
    build: ./admin
    container_name: admin_doctor-appointment
    ports:
      - "3001:80"
